import { useEffect, useMemo, useRef, useState } from "react";
import { GameStage } from "../game/GameStage";
import { VirtualHarmonica } from "../harmonica-ui/VirtualHarmonica";
import { Tuner } from "../components/Tuner";
import { MicrophoneInput, type MicrophoneDiagnostics } from "../audio/MicrophoneInput";
import { PlaybackEngine } from "../audio/PlaybackEngine";
import type { TrackerFrame } from "../audio/tracking";
import { SONGS, parseAbc, type Melody, type MelodyEvent } from "../music/melody";
import { STANDARD_C12, actionsForMidi, type HarmonicaAction } from "../harmonica/profile";
import { noteName } from "../music/pitch";
import { alignPerformance, relativeTargets, transpositionDelta, type InputNoteSegment, type PitchTracePoint } from "../exercises/evaluation";

type Mode = "find" | "score" | "ear";
type Input = "virtual" | "microphone";
type Practice = "step" | "flow";
const player = new PlaybackEngine();

export function App() {
  const [mode, setMode] = useState<Mode>("find"), [input, setInput] = useState<Input>("virtual"), [practice, setPractice] = useState<Practice>("step"), [active, setActive] = useState(0), [status, setStatus] = useState<"idle"|"hit"|"miss">("idle"), [message, setMessage] = useState("Choose a note and play"), [frame, setFrame] = useState<TrackerFrame|null>(null), [trace, setTrace] = useState<PitchTracePoint[]>([]), [micError, setMicError] = useState(""), [diagnostics, setDiagnostics] = useState<MicrophoneDiagnostics>(), [micDevices,setMicDevices]=useState<MediaDeviceInfo[]>([]), [deviceId,setDeviceId]=useState(""), [strict, setStrict] = useState(false), [songKey, setSongKey] = useState("twinkle"), [customAbc, setCustomAbc] = useState(SONGS.twinkle!.abc), [melody, setMelody] = useState(() => parseAbc(SONGS.twinkle!.abc, "twinkle")), [flow, setFlow] = useState(0), [flowResults, setFlowResults] = useState<ReturnType<typeof alignPerformance>>([]), [earRelative, setEarRelative] = useState(true), [earRevealed, setEarRevealed] = useState(false), [earPlayed, setEarPlayed] = useState<number[]>([]), [session, setSession] = useState({ hits: 0, attempts: 0 }), [showSettings, setShowSettings] = useState(false);
  const microphone = useRef(new MicrophoneInput()), flowTimer = useRef<number | undefined>(undefined), flowStart = useRef(0), performed = useRef<InputNoteSegment[]>([]), stableSince = useRef(0), stableMidi = useRef<number | undefined>(undefined), submittedMidi = useRef<number | undefined>(undefined);
  const findMidi = [60,62,64,65,67,69,71,72][active % 8]!, earTargets = [60,64,62,67], sourceEvents = useMemo<MelodyEvent[]>(() => mode === "find" ? [{ id: "target", kind: "note", startBeat: 0, durationBeats: 2, midi: findMidi, measureIndex: 0 }] : mode === "ear" ? earTargets.map((midi,index)=>({ id:`ear-${index}`,kind:"note",startBeat:index,durationBeats:1,midi,measureIndex:0 })) : melody.events, [mode, findMidi, melody]);
  const targetNotes = sourceEvents.filter((event) => event.kind === "note");
  const target = targetNotes[Math.min(active, targetNotes.length - 1)];
  const calibrationSamples = useMemo(() => JSON.parse(localStorage.getItem("harmonica-calibration-samples") ?? "{}") as Record<number, number[]>, [showSettings]);
  const expectedOffset = (midi?: number) => { const values = midi === undefined ? [] : calibrationSamples[midi] ?? []; const sorted = [...values].sort((a,b)=>a-b); return sorted[Math.floor(sorted.length/2)] ?? 0; };

  useEffect(() => () => { microphone.current.stop(); player.stop(); if (flowTimer.current) cancelAnimationFrame(flowTimer.current); }, []);
  useEffect(() => { if (input !== "microphone") { microphone.current.stop(); setFrame(null); setTrace([]); return; } submittedMidi.current=undefined; void microphone.current.start((next) => { setFrame(next); if (!next) { stableMidi.current=undefined; submittedMidi.current=undefined; return; } setTrace((value) => [...value.slice(-149), { time: next.time, midiFloat: next.midiFloat, clarity: next.clarity, rms: next.rms }]); if (next.state === "stable") { if (stableMidi.current !== next.classifiedMidi) { stableMidi.current=next.classifiedMidi; stableSince.current=next.time; submittedMidi.current=undefined; } if (next.time-stableSince.current>=120 && submittedMidi.current!==next.classifiedMidi) { submittedMidi.current=next.classifiedMidi; submitMidi(next.classifiedMidi, undefined, next); } } }, deviceId || undefined).then((value)=>{setDiagnostics(value);void MicrophoneInput.devices().then(setMicDevices)}).catch((error: unknown) => { setMicError(error instanceof Error ? error.message : "Microphone unavailable"); setInput("virtual"); }); }, [input, deviceId, mode, practice, active, strict]);

  const flash = (next: "hit"|"miss", text: string) => { setStatus(next); setMessage(text); window.setTimeout(() => setStatus("idle"), 420); };
  const submitMidi = (midi: number, action?: HarmonicaAction, live?: TrackerFrame) => {
    if (!target) return;
    setSession((value) => ({ ...value, attempts: value.attempts + 1 }));
    if (mode === "ear") { handleEar(midi); return; }
    if (practice === "flow") { if (action) performed.current.push(segmentFromVirtual(midi, performance.now() - flowStart.current, 300)); else if(live) performed.current.push(segmentFromLive(live,performance.now()-flowStart.current)); return; }
    const exactAction = mode === "find" && input === "virtual" ? action?.canonicalMidi === target.midi : midi === target.midi;
    const centsOkay = !strict || !live || Math.abs((live.midiFloat - Math.round(live.midiFloat)) * 100 - expectedOffset(live.classifiedMidi)) <= 20;
    if (exactAction && centsOkay) { flash("hit", `Hit · ${noteName(midi)}${input === "microphone" ? ` · ${actionsForMidi(STANDARD_C12,midi).length} possible fingerings` : ""}`); setSession((value) => ({ attempts: value.attempts, hits: value.hits + 1 })); window.setTimeout(() => setActive((value) => mode === "find" ? value + 1 : Math.min(value + 1, targetNotes.length - 1)), 280); }
    else flash("miss", midi === target.midi ? "Right note · adjust intonation" : `${noteName(midi)} · ${midi < (target.midi ?? 0) ? "play higher" : "play lower"}`);
  };
  const handleEar = (midi: number) => {
    const acceptedTargets = earRelative && earPlayed.length ? relativeTargets(earTargets, earPlayed[0]!) : earTargets;
    const expected = acceptedTargets[earPlayed.length] ?? acceptedTargets.at(-1)!;
    if (earRelative && !earPlayed.length) { setEarPlayed([midi]); setActive(1); flash("hit", `Anchor locked at ${noteName(midi)} · phrase transposed`); return; }
    if (midi === expected) { const next = [...earPlayed, midi]; setEarPlayed(next); setActive(Math.min(next.length, earTargets.length - 1)); flash("hit", next.length === earTargets.length ? "Pitches found · now perform the rhythm" : "Interval found"); if (next.length === earTargets.length) setEarRevealed(true); }
    else { const candidate = [...earPlayed, midi], delta = !earRelative ? transpositionDelta(earTargets, candidate) : null; flash("miss", delta && delta !== 0 ? `Intervals match · phrase is ${Math.abs(delta)} semitone${Math.abs(delta)===1?"":"s"} ${delta>0?"high":"low"}` : `${noteName(midi)} · target remains hidden`); }
  };
  const onVirtualEnd = (action: HarmonicaAction, duration: number) => { void player.playNote(action.canonicalMidi, Math.max(.12,duration/1000)); if (practice === "flow") performed.current.push(segmentFromVirtual(action.canonicalMidi, performance.now()-flowStart.current-duration,duration)); else submitMidi(action.canonicalMidi, action); };
  const listen = () => { if (mode === "find" && target?.midi !== undefined) void player.playNote(target.midi); else if (mode === "ear") void player.playMelody({ ...melody, events: earTargets.map((midi,index)=>({id:`ear-${index}`,kind:"note",startBeat:index,durationBeats:1,midi,measureIndex:0})) }); else void player.playMelody(melody); };
  const startFlow = () => { player.stop(); performed.current = []; setFlowResults([]); setActive(0); setMessage("Count in · 4 beats"); const beatMs=60_000/melody.tempoQpm, begins=performance.now()+beatMs*4; flowStart.current=begins; const tick=()=>{ const progress=(performance.now()-begins)/beatMs; setFlow(Math.max(0,progress)); setActive(Math.max(0, Math.min(targetNotes.length-1, targetNotes.findIndex((e)=>e.startBeat+e.durationBeats>progress)))); if(progress <= (melody.events.at(-1)?.startBeat ?? 0)+(melody.events.at(-1)?.durationBeats ?? 0)){ flowTimer.current=requestAnimationFrame(tick); } else { setFlowResults(alignPerformance(melody.events, performed.current, melody.tempoQpm)); setMessage("Run complete · review separate scores below"); }}; flowTimer.current=requestAnimationFrame(tick); };
  const loadSong = (key: string) => { const item=SONGS[key]!; setSongKey(key); setCustomAbc(item.abc); setMelody(parseAbc(item.abc,key)); setActive(0); setFlow(0); setFlowResults([]); };
  const resetMode = (next: Mode) => { setMode(next); setActive(0); setEarPlayed([]); setEarRevealed(false); setMessage(next === "ear" ? "Listen first · pitches stay hidden" : "Ready"); };

  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="./"><span className="brand-mark">H</span><span><b>Harmonica</b><small>TRAINER</small></span></a><nav>{(["find","score","ear"] as const).map((item)=><button key={item} className={mode===item?"active":""} onClick={()=>resetMode(item)}>{item==="find"?"Find a note":item==="score"?"Play the score":"Play by ear"}</button>)}</nav><div className="top-actions"><a href="?lab=pitch">Labs</a><button aria-label="Settings" onClick={()=>setShowSettings(!showSettings)}>⚙</button></div></header>
    <main>
      <div className="mode-strip"><div><span className="eyebrow">{mode === "find" ? "MODE A · NOTE IDENTITY" : mode === "score" ? "MODE B · SCORE" : "MODE C · EAR"}</span><h1>{mode === "find" ? "Find the note" : mode === "score" ? "Play the score" : "Play it by ear"}</h1></div><div className="session-stats"><span><b>{session.hits}</b> hits</span><span><b>{session.attempts ? Math.round(session.hits/session.attempts*100):100}%</b> identity</span></div></div>
      <div className="toolbar"><div className="segmented"><button className={input==="virtual"?"active":""} onClick={()=>setInput("virtual")}>Virtual</button><button className={input==="microphone"?"active":""} onClick={()=>setInput("microphone")}>Microphone</button></div>{mode!=="find"&&<div className="segmented"><button className={practice==="step"?"active":""} onClick={()=>setPractice("step")}>Step</button><button className={practice==="flow"?"active":""} onClick={()=>setPractice("flow")}>Flow</button></div>}{mode==="ear"&&<div className="segmented"><button className={!earRelative?"active":""} onClick={()=>{setEarRelative(false);setEarPlayed([]);setActive(0)}}>Absolute</button><button className={earRelative?"active":""} onClick={()=>{setEarRelative(true);setEarPlayed([]);setActive(0)}}>Relative</button></div>}<button className="listen" onClick={listen}>▶ Listen</button>{practice==="flow"&&mode!=="find"&&<button className="primary" onClick={startFlow}>Count in + perform</button>}<span className={`feedback-chip ${status}`}>{status==="hit"?"✓":status==="miss"?"↕":"◇"} {message}</span></div>
      {mode==="score"&&<div className="score-source"><select value={songKey} onChange={(e)=>loadSong(e.target.value)}>{Object.entries(SONGS).map(([key,value])=><option key={key} value={key}>{value.title}</option>)}</select><details><summary>Import ABC</summary><textarea value={customAbc} onChange={(e)=>setCustomAbc(e.target.value)}/><button onClick={()=>{try{setMelody(parseAbc(customAbc));setActive(0)}catch(error){setMessage(error instanceof Error?error.message:"Invalid ABC")}}}>Load monody</button></details><label>Tempo <input type="range" min="50" max="160" value={melody.tempoQpm} onChange={(e)=>setMelody((value)=>({...value,tempoQpm:Number(e.target.value)}))}/>{melody.tempoQpm} BPM</label></div>}
      <GameStage events={sourceEvents} activeIndex={Math.max(0,sourceEvents.findIndex((event)=>event.id===target?.id))} hidden={mode==="ear"&&!earRevealed} flowProgress={practice==="flow"?flow:0} trace={trace} status={status} title={mode==="score"?melody.title:mode==="ear"?`${earRelative?"Relative":"Absolute"} phrase`:noteName(findMidi)}/>
      {input === "microphone" ? <section className="input-deck">
        {micDevices.length > 1 && <label className="device-select">Input device <select value={deviceId} onChange={(event) => setDeviceId(event.target.value)}><option value="">System default</option>{micDevices.map((device, index) => <option key={device.deviceId} value={device.deviceId}>{device.label || `Microphone ${index + 1}`}</option>)}</select></label>}
        <Tuner frame={frame} message={micError} expectedOffset={expectedOffset(frame?.classifiedMidi)}/><p className="privacy">🔒 Audio is analyzed on this device and is never uploaded.</p>
      </section> : <VirtualHarmonica onStart={() => {}} onEnd={onVirtualEnd}/>}
      {mode==="ear"&&<div className="ear-tools"><button onClick={()=>setMessage(earPlayed.length?`Next interval: ${earTargets[earPlayed.length]! - earTargets[Math.max(0,earPlayed.length-1)]! >= 0?"up":"down"}`:"Replay the reference")}>Hint</button><button onClick={()=>{setEarRevealed(true);setMessage("Revealed · exercise marked assisted")}}>Reveal</button><span>{earPlayed.length}/{earTargets.length} pitches found</span></div>}
      {!!flowResults.length&&<Review rows={flowResults}/>} 
      {showSettings&&<aside className="settings-drawer"><button className="close" onClick={()=>setShowSettings(false)}>×</button><h2>Practice settings</h2><label><input type="checkbox" checked={strict} onChange={(e)=>setStrict(e.target.checked)}/> Strict intonation ±20¢</label><p>Note identity advances independently of intonation unless strict mode is enabled.</p><a href="?lab=calibration">Instrument calibration →</a><a href="?lab=fixtures">Fixture recorder →</a><a href="?lab=timing">Timing calibration →</a>{diagnostics&&<pre>{JSON.stringify(diagnostics,null,2)}</pre>}</aside>}
    </main><footer><span>Standard C · 12 holes · A4 440 Hz</span><nav><a href="?lab=pitch">Pitch diagnostics</a><a href="?lab=fixtures">Fixture recorder</a><a href="?lab=timing">Timing</a></nav></footer>
  </div>;
}

function Review({rows}:{rows:ReturnType<typeof alignPerformance>}) { const score=(key:"pitch"|"timing"|"length"|"stability"|"intonation")=>Math.round(rows.reduce((sum,row)=>sum+row[key],0)/Math.max(1,rows.length)); return <section className="review"><div><span>Notes</span><b>{score("pitch")}%</b></div><div><span>Timing</span><b>{score("timing")}%</b></div><div><span>Length</span><b>{score("length")}%</b></div><div><span>Stability</span><b>{score("stability")}%</b></div><div><span>Intonation</span><b>{score("intonation")}%</b></div></section> }
function segmentFromVirtual(midi:number,startedAt:number,durationMs:number):InputNoteSegment{return{id:`virtual-${startedAt}`,source:"virtual-harmonica",startedAt,stableStartedAt:startedAt,endedAt:startedAt+durationMs,durationMs,medianFrequencyHz:0,medianMidiFloat:midi,classifiedMidi:midi,medianCentsFromEt:0,centsVariability:0,medianClarity:1,medianRms:1,pitchTrace:[]}}
function segmentFromLive(frame:TrackerFrame,startedAt:number):InputNoteSegment{return{id:`microphone-${startedAt}`,source:"microphone",startedAt,stableStartedAt:startedAt,endedAt:startedAt+180,durationMs:180,medianFrequencyHz:frame.frequencyHz,medianMidiFloat:frame.midiFloat,classifiedMidi:frame.classifiedMidi,medianCentsFromEt:(frame.midiFloat-frame.classifiedMidi)*100,centsVariability:0,medianClarity:frame.clarity,medianRms:frame.rms,pitchTrace:[{time:startedAt,midiFloat:frame.midiFloat,clarity:frame.clarity,rms:frame.rms}]}}
