import JSZip from "jszip";
import { useEffect, useMemo, useRef, useState } from "react";
import { AutocorrelationEstimator, MpmPitchEstimator, YinPitchEstimator, analyzeFrames, syntheticTone } from "../audio/pitch";
import { noteName } from "../music/pitch";
import { MicrophoneInput } from "../audio/MicrophoneInput";
import type { TrackerFrame } from "../audio/tracking";

export function PitchLab() {
  const [algorithm, setAlgorithm] = useState("mpm"), [frameSize, setFrameSize] = useState(4096), [hop, setHop] = useState(256), [midi, setMidi] = useState(60), [results, setResults] = useState<ReturnType<typeof analyzeFrames>>([]);
  const estimator = useMemo(() => algorithm === "yin" ? new YinPitchEstimator(frameSize) : algorithm === "autocorrelation" ? new AutocorrelationEstimator(frameSize) : new MpmPitchEstimator(frameSize), [algorithm, frameSize]);
  const run = (pcm = syntheticTone({ midi, durationSec: 1.2, harmonics: [0.25, 1, .25], noise: .01, vibratoCents: 4 })) => { const before = performance.now(); const data = analyzeFrames(pcm, 48_000, estimator, hop); setResults(data.map((row) => ({ ...row, processingMs: (performance.now() - before) / Math.max(1, data.length) })) as typeof data); };
  return <LabShell title="Pitch laboratory" subtitle="Production estimators, deterministic PCM, and uploaded audio use the same frame analyzer.">
    <div className="lab-controls"><label>Algorithm<select value={algorithm} onChange={(e) => setAlgorithm(e.target.value)}><option value="mpm">MPM / pitchy</option><option value="yin">YIN</option><option value="autocorrelation">Autocorrelation</option></select></label><label>Frame<select value={frameSize} onChange={(e) => setFrameSize(Number(e.target.value))}><option>2048</option><option>4096</option><option>8192</option></select></label><label>Hop<select value={hop} onChange={(e) => setHop(Number(e.target.value))}><option>128</option><option>256</option><option>512</option></select></label><label>Fixture MIDI<input type="number" value={midi} min="48" max="96" onChange={(e) => setMidi(Number(e.target.value))}/></label><button onClick={() => run()}>Run synthetic</button><label className="file-button">Analyze audio<input type="file" accept="audio/*" onChange={async (e) => { const file = e.target.files?.[0]; if (!file) return; const context = new AudioContext(); const decoded = await context.decodeAudioData(await file.arrayBuffer()); run(decoded.getChannelData(0)); await context.close(); }}/></label></div>
    <div className="diagnostic-grid"><Metric label="Frames" value={`${results.length}`}/><Metric label="Tracked note" value={results.length ? noteName(Math.round(results.at(-1)!.midiFloat)) : "—"}/><Metric label="Median cents" value={results.length ? `${Math.round(median(results.map((r) => r.cents)))}¢` : "—"}/><Metric label="Clarity" value={results.length ? median(results.map((r) => r.clarity)).toFixed(3) : "—"}/><Metric label="Sample rate" value="48,000 Hz"/><Metric label="Window / hop" value={`${frameSize} / ${hop}`}/></div>
    <canvas className="waveform" ref={(canvas) => { if (!canvas || !results.length) return; const ctx = canvas.getContext("2d")!; ctx.clearRect(0,0,canvas.width,canvas.height); ctx.strokeStyle="#55ead6"; ctx.beginPath(); results.forEach((r,i) => { const x = i / Math.max(1, results.length - 1) * canvas.width, y = canvas.height/2 - (r.midiFloat-midi)*35; i ? ctx.lineTo(x,y) : ctx.moveTo(x,y); }); ctx.stroke(); }}/>
    <pre className="event-log">{JSON.stringify(results.slice(-8), null, 2)}</pre>
  </LabShell>;
}

export function FixtureRecorder() {
  const [stream, setStream] = useState<MediaStream>(), [recording, setRecording] = useState(false), [clips, setClips] = useState<Array<{ name: string; blob: Blob; expectedMidi: number }>>([]), [target, setTarget] = useState(60); const recorder = useRef<MediaRecorder | undefined>(undefined); const chunks = useRef<Blob[]>([]);
  useEffect(() => () => stream?.getTracks().forEach((track) => track.stop()), [stream]);
  const start = async () => { const active = stream ?? await navigator.mediaDevices.getUserMedia({ audio: { channelCount: 1, echoCancellation: false, noiseSuppression: false, autoGainControl: false } }); setStream(active); chunks.current = []; const media = new MediaRecorder(active); recorder.current = media; media.ondataavailable = (event) => chunks.current.push(event.data); media.onstop = () => { const take = clips.length + 1, name = `midi-${target}-medium-take-${String(take).padStart(2,"0")}.webm`; setClips((value) => [...value, { name, blob: new Blob(chunks.current, { type: media.mimeType }), expectedMidi: target }]); }; media.start(); setRecording(true); };
  const stop = () => { recorder.current?.stop(); setRecording(false); };
  const exportZip = async () => { const zip = new JSZip(); clips.forEach((clip) => zip.file(clip.name, clip.blob)); zip.file("manifest.json", JSON.stringify({ schemaVersion: 1, instrument: { profileId: "standard-c-12", manufacturer: "", model: "", key: "C", holes: 12, valveConfiguration: "unknown", notes: "" }, capture: { browser: navigator.userAgent, sampleRate: 0, channelCount: 1 }, clips: clips.map((clip, index) => ({ file: clip.name, expectedMidi: clip.expectedMidi, dynamic: "medium", take: index + 1, notes: "" })) }, null, 2)); const blob = await zip.generateAsync({ type: "blob" }); download(blob, "harmonica-fixtures.zip"); };
  return <LabShell title="Guided fixture recorder" subtitle="Record room tone, stable notes, bends, and phrases. Audio stays local until you export it."><div className="recorder-guide"><p><b>Protocol:</b> 1 s quiet → clean attack → hold 2–3 s → release → 1 s quiet. Keep the microphone 20–30 cm away.</p><label>Expected MIDI<input type="number" min="48" max="96" value={target} onChange={(e) => setTarget(Number(e.target.value))}/></label><button className={recording ? "danger" : ""} onClick={recording ? stop : start}>{recording ? "■ Stop take" : "● Record take"}</button><button disabled={!clips.length} onClick={exportZip}>Export ZIP + manifest</button></div><ol className="clip-list">{clips.map((clip, index) => <li key={clip.name}>{clip.name}<audio controls src={URL.createObjectURL(clip.blob)}/><button onClick={() => setClips((value) => value.filter((_, i) => i !== index))}>Retake</button></li>)}</ol></LabShell>;
}

export function TimingLab() {
  const [offsets, setOffsets] = useState<number[]>([]), [pulseAt, setPulseAt] = useState(0), [manual, setManual] = useState(Number(localStorage.getItem("harmonica-timing-offset") ?? 0));
  const pulse = () => { const at = performance.now(); setPulseAt(at); setTimeout(() => setPulseAt(0), 180); };
  return <LabShell title="Timing calibration" subtitle="Tap Play now on each visual pulse. The robust median becomes your local input offset."><div className={`timing-orb ${pulseAt ? "pulse" : ""}`}/><div className="lab-controls"><button onClick={pulse}>Pulse</button><button disabled={!pulseAt} onClick={() => setOffsets((value) => [...value, performance.now() - pulseAt])}>Play now</button><label>Manual offset<input type="number" value={manual} onChange={(e) => setManual(Number(e.target.value))}/> ms</label><button onClick={() => { const value = offsets.length ? Math.round(median(offsets)) : manual; localStorage.setItem("harmonica-timing-offset", `${value}`); setManual(value); }}>Save offset</button></div><div className="diagnostic-grid"><Metric label="Samples" value={`${offsets.length}`}/><Metric label="Median" value={`${offsets.length ? Math.round(median(offsets)) : manual} ms`}/><Metric label="Spread" value={`${offsets.length > 1 ? Math.round(Math.max(...offsets)-Math.min(...offsets)) : 0} ms`}/></div></LabShell>;
}

export function CalibrationLab() {
  const [step,setStep]=useState<"noise"|"notes"|"done">("noise"),[frame,setFrame]=useState<TrackerFrame|null>(null),[target,setTarget]=useState(60),[samples,setSamples]=useState<Record<number,number[]>>(()=>JSON.parse(localStorage.getItem("harmonica-calibration-samples")??"{}") as Record<number,number[]>),[error,setError]=useState(""); const mic=useRef(new MicrophoneInput());
  useEffect(()=>{void mic.current.start(setFrame).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:"Microphone unavailable"));return()=>mic.current.stop()},[]);
  const save=()=>{if(!frame||frame.state!=="stable")return;const cents=Math.round((frame.midiFloat-frame.classifiedMidi)*100),next={...samples,[target]:[...(samples[target]??[]),cents]};setSamples(next);localStorage.setItem("harmonica-calibration-samples",JSON.stringify(next));setTarget((value)=>Math.min(96,value+2));setStep("notes")};
  const profile={createdAt:new Date().toISOString(),notes:Object.fromEntries(Object.entries(samples).map(([midi,values])=>[midi,{expectedOffsetCents:Math.round(median(values)),comfortableBandCents:[Math.min(...values)-5,Math.max(...values)+5],variabilityCents:Math.round(Math.max(...values)-Math.min(...values)),samples:values.map((medianCents)=>({medianCents,medianRms:0,variabilityCents:0,durationMs:0}))}]))};
  return <LabShell title="Instrument calibration" subtitle="Identity remains semitone-based; these local centers affect only intonation feedback."><div className="recorder-guide"><p><b>{step==="noise"?"Step 1: keep the room quiet, then continue.":"Step 2: hold the shown note naturally at soft, medium, and loud dynamics."}</b></p><button onClick={()=>setStep("notes")}>{step==="noise"?"Noise measured · continue":"Continue"}</button><label>Target MIDI<input type="number" min="48" max="96" value={target} onChange={(e)=>setTarget(Number(e.target.value))}/></label><button disabled={!frame||frame.state!=="stable"} onClick={save}>Save stable sample</button><button onClick={()=>{localStorage.removeItem("harmonica-calibration-samples");setSamples({})}}>Reset local profile</button><button disabled={!Object.keys(samples).length} onClick={()=>download(new Blob([JSON.stringify(profile,null,2)],{type:"application/json"}),"harmonica-calibration.json")}>Export calibration</button></div><div className="diagnostic-grid"><Metric label="Heard" value={frame?noteName(frame.classifiedMidi):"—"}/><Metric label="Cents" value={frame?`${Math.round((frame.midiFloat-frame.classifiedMidi)*100)}¢`:"—"}/><Metric label="State" value={frame?.state??"silence"}/><Metric label="Samples" value={`${Object.values(samples).flat().length}`}/></div>{error&&<p>{error}</p>}<pre className="event-log">{JSON.stringify(profile,null,2)}</pre></LabShell>
}

function LabShell({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <main className="lab-page"><a className="back-link" href="./">← Trainer</a><span className="eyebrow">DIAGNOSTICS</span><h1>{title}</h1><p>{subtitle}</p>{children}</main>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
function median(values: number[]): number { const sorted = [...values].sort((a,b)=>a-b); return sorted[Math.floor(sorted.length/2)] ?? 0; }
function download(blob: Blob, name: string) { const url = URL.createObjectURL(blob), link = document.createElement("a"); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
