import { describe, expect, test } from "bun:test";
import { AutocorrelationEstimator, MpmPitchEstimator, YinPitchEstimator, analyzeFrames, syntheticTone } from "../../src/audio/pitch";
import { AdaptivePitchTracker, NoteSegmenter } from "../../src/audio/tracking";

describe("deterministic audio",()=>{
  for(const Estimator of [MpmPitchEstimator,YinPitchEstimator,AutocorrelationEstimator]) test(`${Estimator.name} identifies a harmonic tone`,()=>{const pcm=syntheticTone({midi:60,durationSec:.5,harmonics:[.3,1,.2],noise:.002});const rows=analyzeFrames(pcm,48000,new Estimator(4096),512);expect(rows.length).toBeGreaterThan(5);expect(Math.round(rows.at(-1)!.midiFloat)).toBe(60)});
  test("noise below the gate produces no frames",()=>{const pcm=syntheticTone({midi:60,durationSec:.4,harmonics:[0],noise:.001});expect(analyzeFrames(pcm,48000,new MpmPitchEstimator(4096),256)).toHaveLength(0)});
  test("tracker calibrates robustly and rejects broadband, breath, clicks, and out-of-range guesses",()=>{const tracker=new AdaptivePitchTracker();tracker.calibrateNoise([.009,.01,.011,.012,.08]);for(let i=0;i<40;i++)expect(tracker.update({time:i*16,midiFloat:60+(i%7),clarity:.3,rms:.018})).toBeNull();expect(tracker.update({time:700,midiFloat:20,clarity:.99,rms:.2})).toBeNull();expect(tracker.update({time:716,midiFloat:60,clarity:.2,rms:.3})).toBeNull();});
  test("noise followed by a harmonic tone opens promptly and release clears it",()=>{const tracker=new AdaptivePitchTracker(.004);for(let i=0;i<12;i++)tracker.update({time:i*16,midiFloat:60+i%3,clarity:.25,rms:.009});let stable;for(let i=0;i<7;i++)stable=tracker.update({time:200+i*16,midiFloat:60.02,clarity:.95,rms:.08});expect(stable?.state).toBe("stable");for(let i=0;i<5;i++)expect(tracker.update({time:400+i*16,clarity:0,rms:.001})).toBeNull();expect(tracker.lastState).toBe("silence")});
  test("segmenter measures actual duration and separates equal articulated notes",()=>{const frame={time:0,midiFloat:60.02,frequencyHz:262,classifiedMidi:60,state:"stable" as const,clarity:.95,rms:.1};const short=new NoteSegmenter(80);for(let t=0;t<=300;t+=20)short.update({...frame,time:t},t);const shortSegment=short.update(null,400)!;const long=new NoteSegmenter(80);for(let t=0;t<=900;t+=20)long.update({...frame,time:t},t);const longSegment=long.update(null,1000)!;expect(shortSegment.durationMs).toBe(300);expect(longSegment.durationMs).toBe(900);const repeated=new NoteSegmenter(80);for(let t=0;t<=200;t+=20)repeated.update({...frame,time:t},t);expect(repeated.update(null,300)?.durationMs).toBe(200);for(let t=400;t<=600;t+=20)repeated.update({...frame,time:t},t);expect(repeated.update(null,700)?.startedAt).toBe(400)});
});
