import { describe, expect, test } from "bun:test";
import { AutocorrelationEstimator, MpmPitchEstimator, YinPitchEstimator, analyzeFrames, syntheticTone } from "../../src/audio/pitch";
import { AdaptivePitchTracker, NoteSegmenter } from "../../src/audio/tracking";
import { LivePitchState } from "../../src/audio/LivePitchState";
import { analyzePcmThroughProduction } from "../../src/audio/ProductionAudioPipeline";
import { calibrationLooksContaminated } from "../../src/audio/MicrophoneInput";

describe("deterministic audio",()=>{
  for(const Estimator of [MpmPitchEstimator,YinPitchEstimator,AutocorrelationEstimator]) test(`${Estimator.name} identifies a harmonic tone`,()=>{const pcm=syntheticTone({midi:60,durationSec:.5,harmonics:[.3,1,.2],noise:.002});const rows=analyzeFrames(pcm,48000,new Estimator(4096),512);expect(rows.length).toBeGreaterThan(5);expect(Math.round(rows.at(-1)!.midiFloat)).toBe(60)});
  test("noise below the gate produces no frames",()=>{const pcm=syntheticTone({midi:60,durationSec:.4,harmonics:[0],noise:.001});expect(analyzeFrames(pcm,48000,new MpmPitchEstimator(4096),256)).toHaveLength(0)});
  test("tracker calibrates robustly and rejects broadband, breath, clicks, and out-of-range guesses",()=>{const tracker=new AdaptivePitchTracker();tracker.calibrateNoise([.009,.01,.011,.012,.08]);for(let i=0;i<40;i++)expect(tracker.update({time:i*16,midiFloat:60+(i%7),clarity:.3,rms:.018})).toBeNull();expect(tracker.update({time:700,midiFloat:20,clarity:.99,rms:.2})).toBeNull();expect(tracker.update({time:716,midiFloat:60,clarity:.2,rms:.3})).toBeNull();});
  test("noise followed by a soft harmonic tone opens promptly and release clears by elapsed time",()=>{const tracker=new AdaptivePitchTracker(.004);for(let i=0;i<12;i++)tracker.update({time:i*16,midiFloat:60+i%3,clarity:.25,rms:.009});let stable;for(let t=200;t<=420;t+=20)stable=tracker.update({time:t,midiFloat:60.02,clarity:.95,rms:.014});expect(stable?.state).toBe("stable");for(let t=440;t<=780;t+=20)tracker.update({time:t,clarity:0,rms:.001});expect(tracker.lastState).toBe("silence")});
  test("display, accepted, and completed state remain separate through a short dropout",()=>{const live=new LivePitchState(new AdaptivePitchTracker(.004));let bundle;for(let t=0;t<=240;t+=20)bundle=live.update({time:t,midiFloat:60.03,frequencyHz:262,clarity:.95,rms:.02});expect(bundle?.display?.classifiedMidi).toBe(60);expect(bundle?.accepted?.classifiedMidi).toBe(60);const dropout=live.update({time:360,clarity:.1,rms:.001});expect(dropout.display?.classifiedMidi).toBe(60);expect(dropout.accepted?.classifiedMidi).toBe(60);const after=live.update({time:590,clarity:0,rms:.001});expect(after.display).toBeUndefined();expect(after.accepted).toBeUndefined()});
  test("sensitivity presets derive deterministic dB margins",()=>{const high=new AdaptivePitchTracker(.004,.7,[58,99],"high"),normal=new AdaptivePitchTracker(.004,.7,[58,99],"normal"),low=new AdaptivePitchTracker(.004,.7,[58,99],"low");expect(high.openThreshold).toBeLessThan(normal.openThreshold);expect(normal.openThreshold).toBeLessThan(low.openThreshold);expect(normal.openThresholdDb-normal.noiseFloorDb).toBe(6.5)});
  test("soft tones use the same production estimator, gate, latch, and segmenter path",()=>{const pcm=syntheticTone({midi:60,durationSec:1,gain:.035,noise:.0004}),result=analyzePcmThroughProduction(pcm,48000,"normal",512),first=result.bundles.find(bundle=>bundle.accepted);expect(first).toBeDefined();expect(first!.time).toBeLessThan(250);expect(result.segments).toHaveLength(1);expect(result.segments[0]!.classifiedMidi).toBe(60)});
  test("production path survives RMS dropout and vibrato without splitting a note",()=>{const pcm=syntheticTone({midi:64,durationSec:1.2,gain:.08,vibratoCents:18,noise:.001});pcm.fill(0,Math.floor(.55*48000),Math.floor(.65*48000));const result=analyzePcmThroughProduction(pcm,48000,"normal",512);expect(result.segments).toHaveLength(1);expect(result.segments[0]!.classifiedMidi).toBe(64);expect(result.bundles.filter(bundle=>bundle.signalState==="release"&&bundle.display).length).toBeGreaterThan(0)});
  test("production path distinguishes repeated articulation and a stable semitone change",()=>{const tone=syntheticTone({midi:60,durationSec:.45,gain:.08}),gap=new Float32Array(Math.round(.45*48000)),second=syntheticTone({midi:60,durationSec:.45,gain:.08}),joined=new Float32Array(tone.length+gap.length+second.length);joined.set(tone);joined.set(gap,tone.length);joined.set(second,tone.length+gap.length);expect(analyzePcmThroughProduction(joined,48000).segments).toHaveLength(2);const bend=new Float32Array(tone.length+syntheticTone({midi:61,durationSec:.55,gain:.08}).length);bend.set(tone);bend.set(syntheticTone({midi:61,durationSec:.55,gain:.08}),tone.length);expect(analyzePcmThroughProduction(bend,48000).segments.map(segment=>segment.classifiedMidi)).toEqual([60,61])});
  test("contaminated calibration is rejected instead of becoming the noise floor",()=>{expect(calibrationLooksContaminated([.002,.0021,.0022,.018,.025],3)).toBeTrue();expect(calibrationLooksContaminated(Array.from({length:30},(_,index)=>.002+(index%3)*.0001),0)).toBeFalse()});
  test("segmenter measures actual duration and separates equal articulated notes",()=>{const frame={time:0,midiFloat:60.02,frequencyHz:262,classifiedMidi:60,state:"stable" as const,clarity:.95,rms:.1};const short=new NoteSegmenter(80);for(let t=0;t<=300;t+=20)short.update({...frame,time:t},t);const shortSegment=short.update(null,400)!;const long=new NoteSegmenter(80);for(let t=0;t<=900;t+=20)long.update({...frame,time:t},t);const longSegment=long.update(null,1000)!;expect(shortSegment.durationMs).toBe(300);expect(longSegment.durationMs).toBe(900);const repeated=new NoteSegmenter(80);for(let t=0;t<=200;t+=20)repeated.update({...frame,time:t},t);expect(repeated.update(null,300)?.durationMs).toBe(200);for(let t=400;t<=600;t+=20)repeated.update({...frame,time:t},t);expect(repeated.update(null,700)?.startedAt).toBe(400)});
});
