import { useEffect, useRef, useState } from "react";
import { actionFor,type Breath,type HarmonicaAction,type HarmonicaProfile,type Slide } from "../harmonica/profile";
import { teachingNoteName,type NamingSystem } from "../music/naming";
import { HarmonicaBody } from "./HarmonicaBody";
import { slideStateForActions } from "./sliderState";
export function InteractiveHarmonicaView({profile,target,detected=[],onStart,onEnd,showLabels=false,namingSystem="letters",feedback}:{profile:HarmonicaProfile;target?:HarmonicaAction;detected?:HarmonicaAction[];onStart:(action:HarmonicaAction)=>void;onEnd:(action:HarmonicaAction,durationMs:number)=>void;showLabels?:boolean;namingSystem?:NamingSystem;feedback?:{actionId:string;outcome:"correct"|"incorrect"}}){
 const scroll=useRef<HTMLDivElement>(null),started=useRef(new Map<string,number>()),manualUntil=useRef(0),[pressed,setPressed]=useState(new Set<string>()),active=pressed.size?[...pressed].map(id=>profile.physicalActions.find(a=>a.id===id)!).filter(Boolean):target?[target]:detected;
 useEffect(()=>{const root=scroll.current;if(!root||!target||performance.now()<manualUntil.current)return;const element=root.querySelector<HTMLElement>(`[data-hole-group="${target.hole}"]`);if(!element)return;const left=element.offsetLeft-root.clientWidth/2+element.clientWidth/2;if(element.offsetLeft>=root.scrollLeft+root.clientWidth*.2&&element.offsetLeft+element.clientWidth<=root.scrollLeft+root.clientWidth*.8)return;root.scrollTo({left:Math.max(0,left),behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"})},[target?.id,profile.id]);
 const start=(action:HarmonicaAction,key:string)=>{if(started.current.has(key))return;started.current.set(key,performance.now());setPressed(value=>new Set(value).add(action.id));onStart(action)};
 const end=(action:HarmonicaAction,key:string)=>{const at=started.current.get(key);if(at===undefined)return;started.current.delete(key);setPressed(value=>{const next=new Set(value);next.delete(action.id);return next});onEnd(action,performance.now()-at)};
 return <section className="interactive-harmonica-stage" data-testid="interactive-harmonica" data-profile={profile.id} data-slider={slideStateForActions(active)}><div className="interactive-scroll" ref={scroll} onPointerDown={()=>{manualUntil.current=performance.now()+3000}}><HarmonicaBody profile={profile} slider={slideStateForActions(active)}><div className="interactive-holes">{Array.from({length:profile.holeCount},(_,i)=>i+1).map(hole=><div className="interactive-hole" data-hole-group={hole} key={hole}><span>{hole}</span><div>{(["blow","draw"] as Breath[]).flatMap(breath=>(["out","in"] as Slide[]).map(slide=>{const action=actionFor(profile,hole,breath,slide),key=`key-${action.id}`;return <button key={action.id} data-action-id={action.id} data-breath={breath} data-slide={slide} className={`${target?.id===action.id?"guided":""} ${detected.some(item=>item.id===action.id)?"detected":""} ${pressed.has(action.id)?"sounding":""} ${feedback?.actionId===action.id?feedback.outcome:""}`} aria-label={`Hole ${hole}, ${breath}, slide ${slide}${showLabels?`, ${teachingNoteName(action.canonicalMidi,namingSystem)}`:""}`} aria-pressed={pressed.has(action.id)} onPointerDown={event=>{event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);start(action,`pointer-${event.pointerId}`)}} onPointerUp={event=>end(action,`pointer-${event.pointerId}`)} onPointerCancel={event=>end(action,`pointer-${event.pointerId}`)} onKeyDown={event=>{if((event.key===" "||event.key==="Enter")&&!event.repeat){event.preventDefault();start(action,key)}}} onKeyUp={event=>{if(event.key===" "||event.key==="Enter"){event.preventDefault();end(action,key)}}}><i>{breath==="blow"?"↑":"↓"}</i>{showLabels&&<strong>{teachingNoteName(action.canonicalMidi,namingSystem)}</strong>}<small>{slide==="in"?"●│":"● ─"}</small></button>}))}</div></div>)}</div></HarmonicaBody></div></section>
}
