import { Midi } from "@tonejs/midi";
import JSZip from "jszip";
import { analyzePcmThroughProduction } from "../audio/ProductionAudioPipeline";
import type { MelodyEvent, WrittenPitch } from "../music/melody";

export const CANONICAL_PPQ=960;
export const IMPORT_LIMITS={fileBytes:25*1024*1024,mxlExpandedBytes:50*1024*1024,midiEvents:250_000,audioSeconds:15*60} as const;
export type SourceType="midi"|"musicxml"|"audio"|"microphone"|"omr";
export interface ImportWarning{code:string;severity:"info"|"warning"|"error";message:string;sourceLocation?:Record<string,string|number>;eventIds?:string[]}
export interface RawImportedNote{id:string;sourceTrack?:number;sourceChannel?:number;sourcePart?:string;sourceVoice?:string;midi:number;velocity?:number;startTick?:number;durationTick?:number;startSeconds?:number;durationSeconds?:number;cents?:number;rms?:number;pitchTrace?:{offsetMs:number;midiFloat:number;confidence:number}[];writtenPitch?:WrittenPitch}
export interface InventoryItem{id:string;label:string;track?:number;channel?:number;part?:string;voice?:string;program?:number;noteCount:number;minMidi:number;maxMidi:number}
export interface Settings{sourceId:string;strategy:"as-written"|"highest"|"lowest"|"voice-leading";overlapPolicy:"trim-previous"|"prefer-louder"|"prefer-longer"|"reject";grid:"off"|"1/4"|"1/8"|"1/8T"|"1/16"|"1/16T"|"1/32";tempoQpm:number;meter:{numerator:number;denominator:number};prefer:"sharps"|"flats";octaveShift:number;minMidi:number;maxMidi:number}
export interface Candidate{id:string;label:string;sourceDescription:string;rawNotes:RawImportedNote[];canonicalEvents:MelodyEvent[];tempoQpm:number;meter:{numerator:number;denominator:number};key:{tonic:string;mode:string;prefer:"sharps"|"flats"};settings:Settings;warnings:ImportWarning[];metrics:Record<string,number>}
export interface Project{schemaVersion:1;provenance:{sourceType:SourceType;fileName:string;byteLength:number;sha256:string;importer:string;importerVersion:string};sourceSummary:{format:string;inventory:InventoryItem[];tempoChanges:number;meterChanges:number;raw?:unknown};candidates:Candidate[];selectedCandidateId?:string;settingsHash:string}
const enc=new TextEncoder();
export async function sha256(data:Uint8Array|string){const source=typeof data==="string"?enc.encode(data):data,bytes=new Uint8Array(source);return [...new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))].map(x=>x.toString(16).padStart(2,"0")).join("")}
export function stableStringify(value:unknown):string{if(Array.isArray(value))return`[${value.map(stableStringify).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stableStringify(v)}`).join(",")}}`;return JSON.stringify(value)}
const defaults=(sourceId:string):Settings=>({sourceId,strategy:"as-written",overlapPolicy:"trim-previous",grid:"1/16",tempoQpm:100,meter:{numerator:4,denominator:4},prefer:"sharps",octaveShift:0,minMidi:48,maxMidi:84});
const gridTicks=(grid:Settings["grid"])=>({off:1,"1/4":960,"1/8":480,"1/8T":320,"1/16":240,"1/16T":160,"1/32":120}[grid]);
const written=(midi:number,prefer:Settings["prefer"]):WrittenPitch=>{const sharp=["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"],flat=["C","Db","D","Eb","E","F","Gb","G","Ab","A","Bb","B"],name=(prefer==="flats"?flat:sharp)[midi%12]!;return{step:name[0] as WrittenPitch["step"],accidental:name[1]==="#"?"sharp":name[1]==="b"?"flat":undefined,octave:Math.floor(midi/12)-1}}
export function interpret(raw:RawImportedNote[],settings:Settings,sourceHash:string,label="Melody"):Candidate{
 const warnings:ImportWarning[]=[];let notes=[...raw].sort((a,b)=>(a.startTick??0)-(b.startTick??0)||a.midi-b.midi||a.id.localeCompare(b.id));
 if(settings.strategy!=="as-written"){const grouped=new Map<number,RawImportedNote[]>();for(const n of notes){const k=n.startTick??0;grouped.set(k,[...(grouped.get(k)??[]),n])}notes=[...grouped.values()].map(group=>settings.strategy==="lowest"?group[0]!:settings.strategy==="highest"?group.at(-1)!:group.sort((a,b)=>((b.durationTick??0)+(b.velocity??0)*80-Math.abs(b.midi-72)*20)-((a.durationTick??0)+(a.velocity??0)*80-Math.abs(a.midi-72)*20))[0]!)}
 const grid=gridTicks(settings.grid),events:MelodyEvent[]=[];let cursor=0,overlaps=0,rests=0;for(const [i,n] of notes.entries()){let start=settings.grid==="off"?(n.startTick??0):Math.round((n.startTick??0)/grid)*grid;let duration=Math.max(grid,settings.grid==="off"?(n.durationTick??grid):Math.round((n.durationTick??grid)/grid)*grid);if(start<cursor){overlaps++;if(settings.overlapPolicy==="reject"){warnings.push({code:"OVERLAP_REJECTED",severity:"warning",message:`Rejected overlapping source note ${n.id}`,eventIds:[n.id]});continue}start=cursor}if(start>cursor){events.push({id:`${sourceHash.slice(0,12)}-r${i}`,kind:"rest",startBeat:cursor/CANONICAL_PPQ,durationBeats:(start-cursor)/CANONICAL_PPQ,measureIndex:Math.floor(cursor/(CANONICAL_PPQ*settings.meter.numerator))});rests++}const midi=n.midi+settings.octaveShift*12;events.push({id:`${sourceHash.slice(0,12)}-n${i}`,kind:"note",midi,writtenPitch:n.writtenPitch??written(midi,settings.prefer),startBeat:start/CANONICAL_PPQ,durationBeats:duration/CANONICAL_PPQ,measureIndex:Math.floor(start/(CANONICAL_PPQ*settings.meter.numerator))});cursor=start+duration}
 if(overlaps)warnings.push({code:"POLYPHONY_RESOLVED",severity:"warning",message:`Resolved ${overlaps} overlapping notes using ${settings.strategy}/${settings.overlapPolicy}.`});const midis=events.flatMap(e=>e.midi===undefined?[]:[e.midi]),inside=midis.filter(m=>m>=settings.minMidi&&m<=settings.maxMidi).length;
 return{id:`candidate-${sourceHash.slice(0,16)}-${settings.sourceId}-${settings.strategy}`,label,sourceDescription:settings.sourceId,rawNotes:raw,canonicalEvents:events,tempoQpm:settings.tempoQpm,meter:settings.meter,key:{tonic:"C",mode:"major",prefer:settings.prefer},settings,warnings,metrics:{noteCount:midis.length,durationBeats:cursor/CANONICAL_PPQ,minMidi:Math.min(...midis),maxMidi:Math.max(...midis),overlappingNotes:overlaps,restRatio:events.length?rests/events.length:0,insideRangePercent:midis.length?inside/midis.length*100:100,medianInterval:median(midis.slice(1).map((m,i)=>Math.abs(m-midis[i]!))),maxInterval:Math.max(0,...midis.slice(1).map((m,i)=>Math.abs(m-midis[i]!))),noteDensity:cursor?midis.length/(cursor/CANONICAL_PPQ):0,repeatedNoteRatio:midis.length>1?midis.slice(1).filter((m,i)=>m===midis[i]).length/(midis.length-1):0}}
}
const median=(v:number[])=>{const s=[...v].sort((a,b)=>a-b);return s.length?s[Math.floor(s.length/2)]!:0};

export async function importMidi(bytes:Uint8Array,fileName="score.mid"):Promise<Project>{guard(bytes);const hash=await sha256(bytes),midi=new Midi(bytes);let count=0;const inventory:InventoryItem[]=[],candidates:Candidate[]=[];for(const [ti,track] of midi.tracks.entries()){const channels=new Map<number,typeof track.notes>();for(const note of track.notes){count++;const c=track.channel??0;channels.set(c,[...(channels.get(c)??[]),note])}for(const [channel,notes] of channels){const id=`track-${ti}-channel-${channel}`,raw=notes.map((n,i):RawImportedNote=>({id:`${hash.slice(0,12)}-t${ti}c${channel}n${i}`,sourceTrack:ti,sourceChannel:channel,midi:n.midi,velocity:Math.round(n.velocity*127),startTick:Math.round(n.ticks*CANONICAL_PPQ/midi.header.ppq),durationTick:Math.max(1,Math.round(n.durationTicks*CANONICAL_PPQ/midi.header.ppq))})),min=Math.min(...raw.map(n=>n.midi)),max=Math.max(...raw.map(n=>n.midi));inventory.push({id,label:track.name||`Track ${ti+1} · channel ${channel+1}`,track:ti,channel,program:track.instrument.number,noteCount:raw.length,minMidi:min,maxMidi:max});for(const strategy of ["as-written","highest","lowest","voice-leading"] as const){const s={...defaults(id),strategy,tempoQpm:Math.round(midi.header.tempos[0]?.bpm??100),meter:{numerator:midi.header.timeSignatures[0]?.timeSignature[0]??4,denominator:midi.header.timeSignatures[0]?.timeSignature[1]??4}};candidates.push(interpret(raw,s,hash,`${inventory.at(-1)!.label} · ${strategy}`))}}}if(count>IMPORT_LIMITS.midiEvents)throw new Error("MIDI event limit exceeded");const tempoChanges=midi.header.tempos.length,meterChanges=midi.header.timeSignatures.length;for(const c of candidates){if(tempoChanges>1)c.warnings.push({code:"TEMPO_FLATTENED",severity:"warning",message:"Source tempo changes are preserved in inventory but arrangement uses the first tempo."});if(meterChanges>1)c.warnings.push({code:"METER_FLATTENED",severity:"warning",message:"Source meter changes are preserved but arrangement uses the first meter."})}return finish(hash,"midi",fileName,bytes.length,{format:"Standard MIDI",inventory,tempoChanges,meterChanges,raw:{ppq:midi.header.ppq,tempos:midi.header.tempos,timeSignatures:midi.header.timeSignatures}},candidates)}

export async function importMusicXml(bytes:Uint8Array,fileName="score.musicxml"):Promise<Project>{guard(bytes);let xml=new TextDecoder().decode(bytes);if(fileName.toLowerCase().endsWith(".mxl")){const zip=await JSZip.loadAsync(bytes);const files=Object.values(zip.files).filter(f=>!f.dir&&!f.name.includes("..")&&!f.name.startsWith("/"));let expanded=0;for(const f of files)expanded+=(f as { _data?:{uncompressedSize?:number}})._data?.uncompressedSize??0;if(expanded>IMPORT_LIMITS.mxlExpandedBytes)throw new Error("MXL expanded size limit exceeded");const root=files.find(f=>/\.(musicxml|xml)$/i.test(f.name)&&!f.name.includes("META-INF"));if(!root)throw new Error("MXL has no MusicXML score");xml=await root.async("text")}if(/<!DOCTYPE|<!ENTITY/i.test(xml))throw new Error("Unsafe XML declarations are not allowed");const hash=await sha256(bytes),inventory:InventoryItem[]=[],candidates:Candidate[]=[];const parts=[...xml.matchAll(/<part\s+id=["']([^"']+)["'][^>]*>([\s\S]*?)<\/part>/g)];for(const [pi,match] of parts.entries()){const partId=match[1]!,body=match[2]!,div=Number(body.match(/<divisions>(\d+)<\/divisions>/)?.[1]??1),voices=new Map<string,RawImportedNote[]>();let cursor=0,lastStart=0;for(const token of body.matchAll(/<(note|backup|forward)\b[^>]*>([\s\S]*?)<\/\1>/g)){const kind=token[1],b=token[2]!,duration=Number(b.match(/<duration>(\d+)<\/duration>/)?.[1]??0)*CANONICAL_PPQ/div;if(kind==="backup"){cursor-=duration;continue}if(kind==="forward"){cursor+=duration;continue}const chord=/<chord\s*\/>/.test(b),rest=/<rest\b/.test(b),voice=b.match(/<voice>([^<]+)<\/voice>/)?.[1]??"1";if(!chord)lastStart=cursor;if(!rest){const step=b.match(/<step>([A-G])<\/step>/)?.[1]??"C",alter=Number(b.match(/<alter>(-?\d+)<\/alter>/)?.[1]??0),oct=Number(b.match(/<octave>(\d+)<\/octave>/)?.[1]??4),midi=(oct+1)*12+({C:0,D:2,E:4,F:5,G:7,A:9,B:11}[step]??0)+alter,list=voices.get(voice)??[];list.push({id:`${hash.slice(0,12)}-p${pi}v${voice}n${list.length}`,sourcePart:partId,sourceVoice:voice,midi,startTick:chord?lastStart:cursor,durationTick:duration,writtenPitch:{step:step as WrittenPitch["step"],octave:oct,accidental:alter===1?"sharp":alter===-1?"flat":undefined}});voices.set(voice,list)}if(!chord)cursor+=duration}for(const [voice,raw] of voices){const id=`part-${partId}-voice-${voice}`;inventory.push({id,label:`${partId} · voice ${voice}`,part:partId,voice,noteCount:raw.length,minMidi:Math.min(...raw.map(n=>n.midi)),maxMidi:Math.max(...raw.map(n=>n.midi))});candidates.push(interpret(raw,defaults(id),hash,inventory.at(-1)!.label))}}if(!candidates.length)throw new Error("No supported notes found in MusicXML");return finish(hash,"musicxml",fileName,bytes.length,{format:fileName.endsWith(".mxl")?"Compressed MusicXML":"MusicXML",inventory,tempoChanges:(xml.match(/<sound[^>]+tempo=/g)??[]).length,meterChanges:(xml.match(/<time>/g)??[]).length,raw:{xml}},candidates)}

export async function importWav(bytes:Uint8Array,fileName="recording.wav"):Promise<Project>{guard(bytes);const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);if(new TextDecoder().decode(bytes.slice(0,4))!=="RIFF"||new TextDecoder().decode(bytes.slice(8,12))!=="WAVE")throw new Error("Only PCM WAV is supported");const channels=view.getUint16(22,true),rate=view.getUint32(24,true),bits=view.getUint16(34,true);if(bits!==16)throw new Error("WAV must use 16-bit PCM");let pos=12,dataOffset=0,dataSize=0;while(pos+8<=bytes.length){const id=new TextDecoder().decode(bytes.slice(pos,pos+4)),size=view.getUint32(pos+4,true);if(id==="data"){dataOffset=pos+8;dataSize=size;break}pos+=8+size+(size%2)}const frames=Math.floor(dataSize/(2*channels)),seconds=frames/rate;if(seconds>IMPORT_LIMITS.audioSeconds)throw new Error("Audio duration limit exceeded");const pcm=new Float32Array(frames);for(let i=0;i<frames;i++)pcm[i]=view.getInt16(dataOffset+i*channels*2,true)/32768;const analysis=analyzePcmThroughProduction(pcm,rate),hash=await sha256(bytes),raw=analysis.segments.map((s,i):RawImportedNote=>({id:`${hash.slice(0,12)}-a${i}`,midi:s.classifiedMidi,startSeconds:s.startedAt/1000,durationSeconds:s.durationMs/1000,startTick:Math.round(s.startedAt/600*960),durationTick:Math.max(120,Math.round(s.durationMs/600*960)),cents:s.medianCentsFromEt, pitchTrace:s.pitchTrace.map(p=>({offsetMs:p.time-s.startedAt,midiFloat:p.midiFloat,confidence:p.clarity}))})),id="audio-mono",settings={...defaults(id),tempoQpm:100};const inventory=[{id,label:"Production audio pipeline · mono",noteCount:raw.length,minMidi:Math.min(...raw.map(n=>n.midi)),maxMidi:Math.max(...raw.map(n=>n.midi))}];const candidate=interpret(raw,settings,hash,"Audio transcription · explicit 100 BPM grid");candidate.warnings.push({code:"AUDIO_QUANTIZED",severity:"info",message:"Expressive seconds and pitch traces are preserved; notation uses the selected tempo and grid."});return finish(hash,"audio",fileName,bytes.length,{format:"PCM WAV",inventory,tempoChanges:0,meterChanges:0,raw:{sampleRate:rate,channels,durationSeconds:seconds}},[candidate])}
function guard(bytes:Uint8Array){if(bytes.length>IMPORT_LIMITS.fileBytes)throw new Error("Source file size limit exceeded")}
async function finish(hash:string,type:SourceType,fileName:string,byteLength:number,summary:Project["sourceSummary"],candidates:Candidate[]):Promise<Project>{const settingsHash=await sha256(stableStringify(candidates.map(c=>c.settings)));return{schemaVersion:1,provenance:{sourceType:type,fileName:fileName.replace(/[\\/]/g,"_"),byteLength,sha256:hash,importer:"harmonica-score-core",importerVersion:"1.0.0"},sourceSummary:summary,candidates,selectedCandidateId:candidates[0]?.id,settingsHash}}

export function toAbc(c:Candidate){const pitch=(e:MelodyEvent)=>{if(e.kind==="rest")return"z";const w=e.writtenPitch!,mark=w.accidental==="sharp"?"^":w.accidental==="flat"?"_":"",letter=w.octave>=5?w.step.toLowerCase():w.step,oct=w.octave>=6?"'".repeat(w.octave-5):w.octave<4?",".repeat(4-w.octave):"";return mark+letter+oct};return`X:1\nT:${c.label}\nM:${c.meter.numerator}/${c.meter.denominator}\nL:1/16\nQ:1/4=${c.tempoQpm}\nK:${c.key.tonic}\n${c.canonicalEvents.map(e=>`${pitch(e)}${Math.max(1,Math.round(e.durationBeats*4))}`).join(" ")} |\n`}
export function toMidi(c:Candidate){const midi=new Midi();midi.header.fromJSON({...midi.header.toJSON(),ppq:CANONICAL_PPQ});midi.header.setTempo(c.tempoQpm);const track=midi.addTrack();track.name=c.label;for(const e of c.canonicalEvents)if(e.kind==="note")track.addNote({midi:e.midi!,ticks:Math.round(e.startBeat*CANONICAL_PPQ),durationTicks:Math.round(e.durationBeats*CANONICAL_PPQ),velocity:.8});return new Uint8Array(midi.toArray())}
export function toMusicXml(c:Candidate){const notes=c.canonicalEvents.map(e=>e.kind==="rest"?`<note><rest/><duration>${Math.round(e.durationBeats*CANONICAL_PPQ)}</duration><voice>1</voice></note>`:`<note><pitch><step>${e.writtenPitch!.step}</step>${e.writtenPitch!.accidental?`<alter>${e.writtenPitch!.accidental==="sharp"?1:-1}</alter>`:""}<octave>${e.writtenPitch!.octave}</octave></pitch><duration>${Math.round(e.durationBeats*CANONICAL_PPQ)}</duration><voice>1</voice></note>`).join("");return`<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 4.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">\n<score-partwise version="4.0"><work><work-title>${escapeXml(c.label)}</work-title></work><part-list><score-part id="P1"><part-name>Melody</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>${CANONICAL_PPQ}</divisions><key><fifths>0</fifths></key><time><beats>${c.meter.numerator}</beats><beat-type>${c.meter.denominator}</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes><direction><sound tempo="${c.tempoQpm}"/></direction>${notes}</measure></part></score-partwise>\n`}
const escapeXml=(s:string)=>s.replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[x]!));
export async function importScore(bytes:Uint8Array,fileName:string){const ext=fileName.toLowerCase().split(".").pop();if(ext==="mid"||ext==="midi")return importMidi(bytes,fileName);if(ext==="musicxml"||ext==="xml"||ext==="mxl")return importMusicXml(bytes,fileName);if(ext==="wav")return importWav(bytes,fileName);throw new Error("Supported formats: MIDI, MusicXML/MXL, and PCM WAV")}
